### ISSUE TITLE
client tries to connect to localhost:8888 instead of dns name

### ISSUE THREAD

**Issue by rayba** [maestro-server/client-app#8]
**Describe the bug**
I have deployed an evaluation version of maestro with docker-compose and put it behind an ALB with a certificate so that we access it through a url like:
https://maestro.somedomain.nz

When going to login we get "Houston we have a problem" and a network trace (from Chrome dev tools) shows
![image](https://user-images.githubusercontent.com/8020111/78073160-d7575880-73fc-11ea-8c68-8e8e14742c3f.png)

There is a call to http://localhost:8888 which won't work on the client side (unless I am also running the site locally). You can see that the main call is to the domain so that the login page comes up ok.

**To Reproduce**
Deploy behind https with ACM and ALB

**Expected behavior**
the localhost:8888 should not be there for xhr or should work with https

**Screenshots**
If applicable, add screenshots to help explain your problem. (attached)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rayba** [comment]
resolved with docker-compose updates:
```
services:
    client:
        image: maestroserver/client-maestro
        ports:
        - "80:80"
        environment:
        - "API_URL=//maestro.xxx:8888"
        - "STATIC_URL=//maestro.xxx:8888/static"
        - "ANALYTICS_URL=//maestro.xxx:9999"
        - "WEBSOCKET_URL=wss://xxx:8000"
        depends_on:
        - server
```
