### ISSUE TITLE
Issues when accessing profile page on https (AWS ALB)

### ISSUE THREAD

**Issue by rayba** [maestro-server/client-app#9]
**Describe the bug**
When accessing the profile page we receive two errors:
```
centrifuge.js:552 WebSocket connection to 'wss://maestro.xxx:8000/connection/websocket' failed: Error during WebSocket handshake: Unexpected response code: 503
value @ centrifuge.js:552
value @ centrifuge.js:782
(anonymous) @ centrifuge.js:651
```
and 
```
VM23:1 Mixed Content: The page at 'https://maestro.xxx/#/dashboard/profile/settings' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://maestro.xxx:8888/users/upload?ext=jpg&folder=users'. This request has been blocked; the content must be served over HTTPS.
```

**To Reproduce**
docker-compose looks like:
```
services:
    client:
        image: maestroserver/client-maestro
        ports:
        - "80:80"
        environment:
        - "API_URL=//maestro.xxx:8888"
        - "STATIC_URL=//maestro.xxx:8888/static"
        - "ANALYTICS_URL=//maestro.xxx:9999"
        - "WEBSOCKET_URL=wss://maestro.xxx:8000"
        depends_on:
        - server
```
and the AWS Application Load balancer looks like this:
![image](https://user-images.githubusercontent.com/8020111/78089675-996e2a80-7424-11ea-933d-122c535240c9.png)

**Expected behavior**
https/wss would be used consistently. For the most part the site works over https but not for web sockets or this particular API call. 

**Screenshots**
If applicable, add screenshots to help explain your problem. (see above)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome

**Additional context**

**Comment by rayba** [comment]
I believe it may have something to do with `uploaderRepository.js`:

```
const UploaderRepository = (folder) => {

    return {
        upload(_id, type, headers) {
            const filename = `${_id}.${mapsFile(type)}`;

            return new Promise((resolve) => {
                const {authorization, host} = headers;

                resolve({
  ==>             signedRequest: `http://${host}/users/upload?ext=${mapsFile(type)}&folder=${folder}`,
                    filename: `${folder}/${filename}`,
                    headers: {"Content-type": CONTENT_UPLOAD_DEFAULT, "Authorization": authorization}
                });
            });

        },
```

**Comment by Signorini** [comment]
Hello @rayba 

1 - It seems to be the WebSocket service isn't running or there are misconfiguration between lb and WebSocket.

Are you ran the ws service without any customization?. [as example CENTRIFUGO_TLS enabled], the ssl configuration, Is it a full proxy [secure between user and alb and between alb and ws service] or flexible proxy [secure between user and alb but not secure between alb and ws service]?

The ws it's WebSocket + HTTP in the same port, if you spun up a service without any configuration you need to set the alb to not use a secure connection. (user --> https --> alb --> http --> ws)

Check the logs, see if there anything there.

BTW: the [websocket-app](https://github.com/maestro-server/websocket-app) it's a simple wrapper of [centrifugo](https://github.com/centrifugal/centrifugo)


------

2 - The https for assets file, indeed it's a bug, I did a new PR fixing this issue, thanks 
https://github.com/maestro-server/server-app/pull/25

Thanks

**Comment by Signorini** [comment]
Hello @rayba, do you get fixed this issue? thanks

**Comment by rayba** [comment]
I can upload an image successfully, but the image doesn't show. The 403 error is: 
5e83c0adb653890025b678c3.jpg:1 GET https://maestro.xxx:8888/staticusers/5e83c0adb653890025b678c3.jpg?v=1586376283 404

  | baseSetAttr | @ | vue.esm.js:6796
  | setAttr | @ | vue.esm.js:6771
  (truncated)

<img width="313" alt="Capture" src="https://user-images.githubusercontent.com/8020111/78829179-ff1c7100-7a39-11ea-8395-0a0b8fe253b3.PNG">

**Comment by Signorini** [comment]
@rayba 

```
client:
        image: maestroserver/client-maestro
        environment:
        - "STATIC_URL=//maestro.xxx:8888/static/" <------------ it needs to add \
```

Thanks so much to bring this question, definitely, I need to improve the documentation and the code to ensure to be clear in those topics.
